linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - varnamelen
    - wsl
    - exhaustruct
    - depguard

issues:
  exclude-rules:
    - path: _test\.go
      text: "does not use range value in test Run"
      linters:
        - paralleltest
    - path: _test\.go
      linters:
        - lll
        - funlen
        - dupword
