linters-settings:
  errcheck:
    check-type-asserts: true
    check-blank: true
  misspell:
    locale: US

linters:
  enable-all: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - lll
        - funlen
