sudo: false

language: go
go:
  - 1.11.x
  - 1.12.x
  - tip

matrix:
  allow_failures:
  - go: tip

before_install:
  - go get -u github.com/golang/dep/cmd/dep github.com/golangci/golangci-lint/cmd/golangci-lint

install:
  - dep ensure

before_script:
  - golangci-lint run

script:
  - go test -covermode=atomic -coverprofile=coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash)

