sudo: false

language: go
go:
  - 1.6.4
  - 1.7.6
  - 1.8.3
  - 1.9
  - tip

matrix:
  allow_failures:
  - go: tip

before_install:
  - go get -u github.com/Masterminds/glide github.com/golang/lint/golint

install:
  - glide install

before_script:
  - go vet .
  - golint .

script:
  - go test -covermode=atomic -coverprofile=coverage.txt .

after_success:
  - bash <(curl -s https://codecov.io/bash)
