sudo: false

language: go
go:
  - 1.8.5
  - 1.9.2
  - tip

matrix:
  allow_failures:
  - go: tip

before_install:
  - go get -u github.com/golang/dep/cmd/dep github.com/golang/lint/golint honnef.co/go/tools/cmd/staticcheck

install:
  - dep ensure

before_script:
  - go vet
  - golint
  - staticcheck

script:
  - go test -covermode=atomic -coverprofile=coverage.txt .

after_success:
  - bash <(curl -s https://codecov.io/bash)
