sudo: false

language: go
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.18.0

install:
  - GO111MODULE=on go mod vendor

before_script:
  - golangci-lint run ./...

script:
  - go test -covermode=atomic -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
